name: Restricted Branch Check

on:
  workflow_call:
    inputs:
      head_ref:
        description: 'PR head branch'
        required: true
        type: string
      head_repo:
        description: 'PR head repo'
        required: true
        type: string
      pr_number:
        description: 'PR number'
        required: true
        type: string
    secrets:
      JIRA_URL:
        required: true
      JIRA_USERNAME:
        required: true
      JIRA_API_TOKEN:
        required: true
    outputs:
      check_status:
        description: 'Status of the restricted branch check'
        value: ${{ jobs.restricted-branch-check.outputs.status }}

jobs:
  restricted-branch-check:
    name: Check Branch Restrictions
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.branch-check.outputs.status }}
    steps:
      - name: Checkout PR head
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.head_repo }}
          ref: ${{ inputs.head_ref }}
          path: pr-code

      - name: Checkout build-tools repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: master
          path: build-tools

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install rye
          cd build-tools/restriction
          rye sync

      - name: Run restriction checker
        id: branch-check
        env:
          GITHUB_BASE_REF: ${{ github.base_ref }}
          GITHUB_REPOSITORY: ${{ inputs.head_repo }}
          PR_NUMBER: ${{ inputs.pr_number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JIRA_URL: ${{ secrets.JIRA_URL }}
          JIRA_USER: ${{ secrets.JIRA_USERNAME }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        run: |
          echo "status=success" >> $GITHUB_OUTPUT
          (cd build-tools/restriction && rye run restricted-branch-check) || {
            echo "status=failure" >> $GITHUB_OUTPUT
            exit 1
          }

      - name: Generate summary
        if: always()
        run: |
          if [[ "${{ steps.branch-check.outputs.status }}" == "failure" ]]; then
            echo "## ❌ Restricted Branch Check Failed" >> $GITHUB_STEP_SUMMARY
            echo "This PR cannot be merged until all the restricted branch requirements are met." >> $GITHUB_STEP_SUMMARY
          else
            echo "## ✅ Restricted Branch Check Passed" >> $GITHUB_STEP_SUMMARY
            echo "All required approvals are in place for the target branch." >> $GITHUB_STEP_SUMMARY
          fi
